# Check all WP standards via `grunt preflight`

name: WordPress Standards

on:
  push:
    branches: [ develop, master, main ]
  release:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Make sure we are using composer v1
      run: |
        sudo composer self-update --1
        sudo chown $USER $HOME/.composer
    - uses: actions/checkout@v3
    - uses: nanasess/setup-php@master
      with:
        php-version: '7.4'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: composer install
    - run: grunt lint
